# Default values for jaeger-all-in-one.
# This is a YAML-formatted file.

enabled: true
replicaCount: 1

image:
  repository: jaegertracing/all-in-one
  pullPolicy: IfNotPresent
  versionOverride: "*"

healthCheckUrl: /
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
terminationGracePeriodSeconds: 10

environmentVariables:
  MEMORY_MAX_TRACES: 100000
  SPAN_STORAGE_TYPE: badger
  BADGER_EPHEMERAL: false
  BADGER_DIRECTORY_VALUE: /badger/data
  BADGER_DIRECTORY_KEY: /badger/key

enableHttpZipkinCollector: false
enableHttpOpenTelemetryCollector: false

serviceAccount:
  create: true
  name:

podAnnotations: 
  prometheus.io/scrape: "true"
  prometheus.io/path: "/metrics"
  prometheus.io/port: "14269"

podSecurityContext:
  fsGroup: 0

securityContext:
  runAsUser: 0  
  runAsGroup: 0

service:
  type: ClusterIP
  port: 16686
  annotations:
    prometheus.io/probe: "true"
    prometheus.io/probe-path: "/"
  headless:
    annotations: {}

ingress:
  enabled: true
  className: nginx  # <- Đã thay thế annotation cũ
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "false"
  hosts:
    - host: jaeger.vmt.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: jaeger-tls
  #    hosts:
  #      - jaeger.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

volume:
  enabled: true
  className: ""
  size: 3Gi

tests:
  enabled: true

livenessProbe:
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3
  successThreshold: 1
