apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rag-nginx-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /rag/docs(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.httpPort.port }}
          - path: /rag/openapi.json(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.httpPort.port }}
          - path: /ask(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.httpPort.port }}
          - path: /healthz(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.service.name }}
                port:
                  number: {{ .Values.service.httpPort.port }}
